AllowedHosts: "*"
Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
MarvelApiConfig:
  Hash: cefcb75986845fd7caf2Zab2d805c130
  PublicKey: 5daf0826df6196c9Z52561eed5cfa328
  Timestamp: 1
  Url: "https://gateway.marvel.com:443"
Message:
  HelloWorld: "The most famous message in the developer community. - CHANGED"
